### ISSUE TITLE
Google BigQuery Auth Issues

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/rusty_connect#2]
## Overview
When requests are sent to the `/up` endpoint, the up check is unable to connect to BigQuery. I've mounted the .json key to the docker container, but I think there may be another step. 

## Steps to Replicate
1) `Post` sent to endpoint
```curl
curl --location 'https://a11y-connect.beltway.cloud/up' \
--header 'x-auth: [api-key]' \
--header 'Content-Type: application/json' \
--data '{"target": "https://bentleyhensel.com"}'
```
2) Response
```
failed to store data to google big query: Invalid service account key (error: Bad authorized user secret: missing field `client_secret` at line 12 column 1)
```

1) Send `POST` request with empty body
```
curl --location --request POST 'https://a11y-connect.beltway.cloud/up' \
--header 'x-auth: [api-key]'
```

2) Response
```
failed to read target list from google big query: Invalid service account key (error: Bad authorized user secret: missing field `client_secret` at line 12 column 1)
```

## Additional Information
I found [this Stack Exchange issue](https://stackoverflow.com/questions/64937089/invalid-service-account-key-on-google-cloud-platform) that seems applicable

## Acceptance Criteria
- [ ] BigQuery authenticating with application
- [ ] Up can read dataset.domains
- [ ] Up can write to dataset.domains

**Comment by lem-solutions** [comment]
looks like there's something wrong with your json file. I'm not very familiar with google's terminology so maybe the needed file is actually called something else than expected, idk, but the needed json file looks something like this: 

```
{
  "client_id": "[noise].apps.googleusercontent.com",
  "client_secret": "[noise]",
  "refresh_token": "[noise]",
  "type": "authorized_user"
}
```

**Comment by TheBoatyMcBoatFace** [comment]
Agh that makes sense. I'm playing around with the auth file this evening and will let you know how it goes.

**Comment by TheBoatyMcBoatFace** [comment]
Apologies for delayed response, Github notifications are the worst

**Comment by TheBoatyMcBoatFace** [comment]
Resolved by 
- https://github.com/TheBoatyMcBoatFace/rusty_connect/commit/9b42f1f309832fea789cef5e90d7015e0452f851
